FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc curl libpq-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["celery", "-A", "saasproject", "worker", "--concurrency=1", "-l", "info"]